app/routes/auth_routes.py
#!/usr/bin/env python3
"""Auth Routes for the app"""
from flask import Blueprint, render_template, redirect, url_for, flash, request, current_app
from flask_login import login_user, logout_user, login_required, current_user
from ..models import db, User, Role
from ..forms import SignupForm, SigninForm, ProfileUpdateForm
from ..utils.upload_sets import photos

auth_routes = Blueprint('auth_routes', __name__, url_prefix='/auth')

@auth_routes.route('/signup', methods=['GET', 'POST'])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, password=form.password.data)
        
        """role_name = form.role.data
        role = Role.query.filter_by(name=role_name).first()
        if role:
            new_user.roles.append(role)
        else:
            flash('Invalid role selected. Please try again.')
            return render_template('signup.html', form=form)"""

        db.session.add(new_user)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main_routes.index'))
    return render_template('signup.html', form=form)


@auth_routes.route('/signin', methods=['GET', 'POST'])
def signin():
    form = SigninForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user)
            flash('Successfully signed in.')
            return redirect(url_for('main_routes.index'))
        else:
            flash('Invalid email or password. Please try again.')
    return render_template('signin.html', form=form)


@auth_routes.route('/signout', methods=['GET'])
@login_required
def signout():
    """Sign out the current user and redirect to the home page"""
    logout_user()
    flash('Successfully logged out.')
    return redirect(url_for('main_routes.index'))


@auth_routes.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = ProfileUpdateForm(obj=current_user)

    if form.validate_on_submit():
        if form.user_image.data:
            filename = photos.save(form.user_image.data)
            current_user.image_path = filename
        current_user.bio = form.bio.data
        current_user.discord_id = form.discord_id.data
        current_user.github_username = form.github_username.data
        current_user.linkedin_link = form.linkedin_link.data
        current_user.twitter_link = form.twitter_link.data
        current_user.website_link = form.website_link.data
        db.session.commit()
        flash('Profile updated successfully!', 'success')
        return redirect(url_for('auth_routes.account'))

    return render_template('account.html', current_user=current_user, form=form)


@auth_routes.route('/change_password', methods=['POST'])
@login_required
def change_password():
    current_password = request.form.get('current_password')
    new_password = request.form.get('new_password')
    confirm_password = request.form.get('confirm_password')

    # Verify that the current password is correct
    if not current_user.check_password(current_password):
        flash('Current password is incorrect.')
        return redirect(url_for('auth_routes.account'))

    # Verify that the new password and confirmation match
    if new_password != confirm_password:
        flash('New password and confirmation do not match.')
        return redirect(url_for('auth_routes.account'))

    # Update the user's password
    current_user.set_password(new_password)
    db.session.commit()

    flash('Your password has been updated.')
    return redirect(url_for('auth_routes.account'))

app/routes/main_routes.py
#!/usr/bin/env python3
"""Main Routes for the Flask application"""
# app/routes/main_routes.py
from flask import render_template, Blueprint
from flask_login import current_user
from app.models import User

main_routes = Blueprint('main_routes', __name__, url_prefix='')

@main_routes.route('/')
def index():
    return render_template('base.html', include_header=True, current_user=current_user)

@main_routes.route('/about')
def about():
    employees = User.query.all()
    return render_template('about.html', include_header=True, current_user=current_user, employees=employees)

@main_routes.route('/business_plan')
def business_plan():
    return render_template('business_plan.html', include_header=True, current_user=current_user)

app/routes/project_routes.py
#!/usr/bin/env python3
"""Project Routes for the Flask application"""
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required, current_user
from app import db
from app.models import Project, User, Role
from app.forms import ProjectForm

project_routes = Blueprint('project_routes', __name__, url_prefix='/projects')


@project_routes.route('/add_project', methods=['GET', 'POST'])
@login_required
def add_project():
    form = ProjectForm()
    form.related_users.choices = [(u.id, u.username) for u in User.query.all()]
    form.roles.choices = [(r.id, r.name) for r in Role.query.all()]
    if form.validate_on_submit():
        new_project = Project(
            name=form.name.data,
            description=form.description.data,
            status=form.status.data,
            author_id=current_user.id,
            version=form.version.data,
            meeting_days=form.meeting_days.data,
            repo_link=form.repo_link.data
        )
        related_users = User.query.filter(
            User.id.in_(form.related_users.data)).all()
        roles = Role.query.filter(Role.id.in_(form.roles.data)).all()
        new_project.related_users = related_users
        new_project.roles = roles
        new_project.related_users.append(current_user)
        db.session.add(new_project)
        db.session.commit()
        flash('Project added successfully.', 'success')
        return redirect(url_for('project_routes.view_project',
                                current_user=current_user,
                                project_id=new_project.id))
    return render_template('projects.html', form=form)


@project_routes.route('/<project_id>')
@login_required
def view_project(project_id):
    project = Project.query.get_or_404(project_id)
    form = ProjectForm(obj=project)
    return render_template('view_project.html', project=project, form=form,
                           current_user=current_user)


@project_routes.route('/')
@login_required
def all_projects():
    projects = Project.query.all()
    form = ProjectForm()
    return render_template('all_projects.html', projects=projects, form=form,
                           current_user=current_user)


@project_routes.route('/delete_project/<project_id>', methods=['POST'])
@login_required
def delete_project(project_id):
    if not current_user.has_role('ADMIN'):
        flash('You do not have permission to delete projects.')
        return redirect(url_for('project_routes.all_projects'))
    project = Project.query.get(project_id)
    if project:
        db.session.delete(project)
        db.session.commit()
        flash('Project deleted successfully.')
    else:
        flash('Project not found.')
    return redirect(url_for('project_routes.all_projects'))


@project_routes.route('/update_project/<project_id>', methods=['GET', 'POST'])
@login_required
def update_project(project_id):
    project = Project.query.get(project_id)
    if project is None:
        flash('Project not found.')
        return redirect(url_for('project_routes.all_projects'))

    form = ProjectForm(obj=project)
    form.related_users.choices = [(u.id, u.username) for u in User.query.all()]
    form.roles.choices = [(r.id, r.name) for r in Role.query.all()]

    if form.validate_on_submit():
        # Update the project with the new data from the form
        project.name = form.name.data
        project.description = form.description.data
        project.status = form.status.data
        project.version = form.version.data
        related_users = User.query.filter(
            User.id.in_(form.related_users.data)).all()
        roles = Role.query.filter(Role.id.in_(form.roles.data)).all()
        project.related_users = related_users
        project.roles = roles
        project.meeting_days = form.meeting_days.data
        project.repo_link = form.repo_link.data
        db.session.commit()
        flash('Project updated successfully.')
        return redirect(url_for('project_routes.update_project', project_id=project.id,
                                current_user=current_user))

    return render_template('view_project.html', form=form, project=project,
                           current_user=current_user)


@project_routes.route('/<project_id>/join', methods=['POST'])
@login_required
def add_user_to_project(project_id):
    user = current_user
    project = Project.query.get(project_id)
    if project is None:
        flash('Project not found.')
        return redirect(url_for('project_routes.all_projects'))
    if user not in project.related_users:
        project.related_users.append(user)
        db.session.commit()
        flash('You have joined the project.')
    else:
        flash('You are already a member of this project.')
    return redirect(url_for('project_routes.view_project', project_id=project.id,
                            current_user=current_user))

app/templates/default/footer.html
<footer class="mt-3 py-2 bg-dark text-light">
  <div class="container">
    <div class="row">
      <section class="col-md-4">
        <h5>About</h5>
        <p>C19 Project Management System</p>
      </section>
      <nav class="col-md-4">
        <h5>Quick Links</h5>
        <ul>
          <li><a href="#">To Top</a></li>
        </ul>
      </nav>
      <address class="col-md-4">
        <h5>Contact</h5>
        <ul class="list-unstyled text-light">
        </ul>
      </address>
    </div>
    <div class="row mt-3">
      <div class="col text-center">
        <p>&copy; self.__name__</p>
        <p></p>
      </div>
    </div>
  </div>
</footer>

app/templates/default/header.html
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="#">
      <img
        src="{{ url_for('static', filename='images/trainbottwo.png') }}"
        alt="Logo"
        width="auto"
        height="30"
      />
    </a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main_routes.index') }}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main_routes.about') }}"
            >About</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main_routes.business_plan') }}"
            >Business Plan</a
          >
        </li>
      </ul>

      <ul class="navbar-nav nav-account">
        {% if not current_user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth_routes.signup') }}"
            >Sign Up</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth_routes.signin') }}"
            >Sign In</a
          >
        </li>
        {% else %}
        <li class="nav-item">
          <a
            class="nav-link"
            href="{{ url_for('auth_routes.account', user_id=current_user.id) }}"
            >My Account</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('auth_routes.signout') }}"
            >Sign Out</a
          >
        </li>
        {% if current_user.is_authenticated and current_user.has_role('C19') %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('project_routes.add_project') }}"
            >Add Project</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link"
            href="{{ url_for('project_routes.all_projects') }}"
            >List Projects</a
          >
          {% endif %} {% endif %}
        </li>
      </ul>
    </div>
  </nav>
</header>

app/templates/default/links.html
<!-- FavIco -->
<link
  rel="icon"
  type="image/png"
  href="{{ url_for('static', filename='images/favicon.ico') }}"
/>

<!-- Bootstrap CSS -->
<link
  rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
/>

<!-- Richard CSS -->
<link
  href="{{ url_for('static', filename='styles/richard.css', v='1.1.4') }}"
  rel="stylesheet"
/>

app/templates/default/meta.html
<meta
  name="description"
  content="Diamond Paws is more than just a company; we are a community of passionate learners and innovators. Our members come from diverse backgrounds, but we all share a common goal: to become skilled software engineers. We offer a supportive environment where members can work on real-world projects, learn from each other, and grow both personally and professionally."
/>
<meta
  name="keywords"
  content="Tulsa, Software, Engineering, Machine Learning, Full Stack, AR, VR, Service, Contract, Freelance, Web, Mobile, App, Development, Design,"
/>
<meta name="author" content="Chris Stamper" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta charset="UTF-8" />